### ISSUE TITLE
[BUG] use-capital: true and use-hyphen: true conflict - kebab-case still enforced when capitals are allowed

### ISSUE THREAD

**Issue by ahmetenesdemir** [ahmet-enes-demir/pre-commit-filename-linter#6]
**Describe the bug**
When both `use-capital: true` and `use-hyphen: true` are set in the configuration, the linter still enforces kebab-case and rejects files with capital letters, ignoring the `use-capital` setting.

**To Reproduce**
1. Run command `python3 src/file_name_checker.py --config .naming-convention.yaml testFile.txt`
2. With configuration that has both `use-capital: true` and `use-hyphen: true`
3. See error `testFile.txt: Files should use kebab-case (use hyphens(-) in the filename)`

**Expected behavior**
Files with capital letters should be allowed when `use-capital: true` is set, regardless of the `use-hyphen` setting. The file `testFile.txt` should pass validation.

**Configuration**
```yaml
files:
  use-hyphen: true
  use-capital: true
  use-underscore: false
  allow-spaces: false
  require-descriptive: true
  min-length: 3
  max-length: 50
  allow-unicode: false
```

**Environment:**
- OS: macOS
- Python version: 3.13.5
- Pre-commit version: 3.7.0

**Additional context**
The kebab-case validation appears to run before or override the capital letter validation, causing conflicts when both options are enabled. The validation logic should respect the use-capital: true setting and skip kebab-case enforcement when capitals are explicitly allowed.
Expected: Should pass validation
